name: Upload Storybook and release

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
    - uses: webfactory/ssh-agent@v0.2.0
      with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
    - run: npm run deploy-storybook -- --ci
    - run: npm run semantic-release
    - run: npm run warm
      env:
        CI: true
        HUSKY_SKIP_HOOKS: 1
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
